[package]
name = "prot"
version = "0.1.0"
edition.workspace = true
authors.workspace = true

[dependencies]
serde = "1.0.204"
postcard = "1.0.8"
tokio = { version="1", features = ["net", "io-util"] }
tracing = "0.1.40"
